export const POKEMON_TYPES: { [key: string]: string } = {
  grass: 'Planta',
  poison: 'Veneno',
  fire: 'Fuego',
  flying: 'Volador',
  water: 'Agua',
  bug: 'Bicho',
  normal: 'Normal',
  electric: 'Eléctrico',
  ground: 'Tierra',
  fairy: 'Hada',
  fighting: 'Lucha',
  psychic: 'Psíquico',
  rock: 'Roca',
  steel: 'Acero',
  ice: 'Hielo',
  ghost: 'Fantasma',
  dragon: 'Dragón',
  dark: 'Siniestro',
};
